var ASSUMPTIONS = [
    { id: "baseJurorHourlyPay", category: "Adaptive case pricing", label: "Base juror hourly pay", min: 6, max: 40, step: 1, default: 12, low: 8, high: 24, format: "money", confidence: "pricing rule", affects: ["pricing", "supply", "lazy", "bribe", "appeal"], copy: "What it means: The starting hourly rate before eligible-supply pressure, expected time, case complexity, and panel size build the required panel compensation." },
    { id: "targetSeatsPerJuror", category: "Adaptive case pricing", label: "Target monthly seats per active juror", min: 1, max: 20, step: .5, default: 4, low: 2, high: 8, format: "number", confidence: "pricing rule", affects: ["pricing", "lazy", "bribe", "appeal"], copy: "What it means: The workload level used to reprice juror pay. More seats per eligible juror raise the quote; more supply lowers it." },
    { id: "processingCostPerCase", category: "Adaptive case pricing", label: "Processing cost per jury case", min: 0, max: 20, step: 1, default: 3, low: 1, high: 8, format: "money", confidence: "approved cost", affects: ["pricing"], copy: "What it means: The published non-juror processing cost included in each deterministic court fee." },
    { id: "operationsMonthlyBudget", category: "Adaptive case pricing", label: "Approved monthly operations budget", min: 0, max: 25000, step: 500, default: 4000, low: 2000, high: 10000, format: "money", confidence: "governance budget", affects: ["pricing"], copy: "What it means: The public operating budget spread across expected cases before the per-case cap applies." },
    { id: "operationsCaseCap", category: "Adaptive case pricing", label: "Operations charge cap per case", min: 0, max: 500, step: 10, default: 100, low: 50, high: 250, format: "money", confidence: "constitutional cap", affects: ["pricing"], copy: "What it means: The most one case may contribute to operations, even when the approved budget is larger." },
    { id: "reserveFloorVotes", category: "Juror money at risk and effort", label: "Minimum votes covered by money at risk", min: 0, max: 3, step: .1, default: 1, low: .3, high: 2, format: "number", confidence: "modeling floor", affects: ["reserve", "supply"], copy: "What it means: Even when the court is quiet, jurors are modeled as having money at risk for at least this many votes. This keeps skin in the game instead of letting lazy voting become free." },
    { id: "reserveElasticity", category: "Juror money at risk and effort", label: "How fast money at risk grows with workload", min: .6, max: 1.4, step: .05, default: 1, low: .8, high: 1.2, format: "mult", confidence: "medium", affects: ["reserve", "supply"], copy: "What it means: How aggressively required money at risk rises as each juror gets more pending work. At 1.0 it scales linearly." },
    { id: "reservePayMultiple", category: "Juror money at risk and effort", label: "Pending pay at risk per priced vote", min: 1, max: 12, step: .25, default: 6, low: 3, high: 9, format: "mult", confidence: "design rule", affects: ["reserve", "lazy", "bribe", "supply"], copy: "What it means: The amount of pending compensation exposed for each priced vote, measured as a multiple of base vote pay. This is independent of the expected mistake rate, so the deterrence margin can genuinely widen or narrow." },
    { id: "lazyShortcutShare", category: "Juror money at risk and effort", label: "Shortcut benefit relative to normal vote pay", min: .1, max: 1, step: .05, default: .5, low: .25, high: .75, format: "pct", confidence: "low", affects: ["lazy"], copy: "What it means: The modeled value of compensation retained plus research effort avoided when a juror votes carelessly instead of checking the evidence." },
    { id: "reserveExitBurden", category: "Juror money at risk and effort", label: "Money-at-risk burden jurors tolerate", min: 4, max: 80, step: 1, default: 40, low: 18, high: 60, format: "number", confidence: "low", affects: ["supply", "capture"], copy: "What it means: How many months of pay a juror will tolerate having at risk before the work feels too costly and they leave." },
    { id: "reserveExitSharpness", category: "Juror money at risk and effort", label: "How fast jurors leave when burden is high", min: .6, max: 4, step: .1, default: 2, low: 1.2, high: 3, format: "number", confidence: "low", affects: ["supply", "capture"], copy: "What it means: Whether jurors leave gradually or sharply once money at risk exceeds their tolerance." },
    { id: "reserveExitMax", category: "Juror money at risk and effort", label: "Most jurors who can leave from high burden", min: .05, max: .8, step: .05, default: .45, low: .25, high: .65, format: "pct", confidence: "low", affects: ["supply", "capture"], copy: "What it means: The maximum share of jurors that can be priced out by high money-at-risk requirements." },
    { id: "faceSurvival", category: "Accounts and vote privacy", label: "Rented accounts passing face checks", min: 0, max: .5, step: .01, default: .05, low: .01, high: .15, format: "pct", confidence: "low", affects: ["rental", "capture"], copy: "What it means: The share of rented accounts assumed to survive live face checks. This is a modeled leak rate, not a measured biometric failure rate." },
    { id: "ballotResidualRisk", category: "Accounts and vote privacy", label: "Paid delivery enforceable despite privacy", min: 0, max: .01, step: .0001, default: .0001, low: 0, high: .0005, format: "pct", confidence: "modeling floor", affects: ["bribe"], copy: "What it means: The modeled probability that a briber can still verify or enforce paid delivery even though re-keyable threshold ballots produce no transferable vote receipt." },
    { id: "drawPoolShare", category: "Jury selection and attacker control", label: "Active jurors available for drawing", min: .2, max: 1, step: .05, default: .8, low: .5, high: 1, format: "pct", confidence: "medium", affects: ["capture", "panel"], copy: "What it means: The share of signed-up jurors who are active, online, holding enough stake, and eligible to be randomly drawn." },
    { id: "coordinationReadyShare", category: "Jury selection and attacker control", label: "Coordinated attackers who become drawable", min: .02, max: .4, step: .01, default: .12, low: .05, high: .25, format: "pct", confidence: "medium", affects: ["capture"], copy: "What it means: The share of recruited attackers who actually remain qualified, accurate enough, active, available, and drawable in the same voting window. It models coordination logistics, not biometric failure." },
    { id: "seniorPoolShare", category: "Jury selection and attacker control", label: "Jurors eligible for largest juries", min: .15, max: 1, step: .05, default: .45, low: .25, high: .75, format: "pct", confidence: "medium", affects: ["capture", "panel"], copy: "What it means: The share of jurors with enough history and aptitude tests to be eligible for large 31-person juries." },
    { id: "parallelPanels", category: "Jury selection and attacker control", label: "Minimum parallel juries", min: 1, max: 5, step: 1, default: 1, low: 1, high: 3, format: "int", confidence: "scaled design rail", affects: ["capture", "panel"], copy: "What it means: A scaled-protocol rule that can require several independent juries to agree before a large case finalizes. It is not part of the three-juror demonstration." },
    { id: "consentedTestShare", category: "Juror aptitude tests", label: "Real cases used in aptitude tests", min: 0, max: .25, step: .01, default: .04, low: .01, high: .12, format: "pct", confidence: "medium", affects: ["drift", "keys"], copy: "What it means: The percentage of ordinary disputes, with disputant consent, used as hidden aptitude tests to grade jurors." },
    { id: "keyScaleFloor", category: "Juror aptitude tests", label: "Minimum aptitude tests before trusting a grade", min: 1, max: 12, step: .5, default: 3, low: 2, high: 6, format: "number", confidence: "medium", affects: ["drift"], copy: "What it means: The minimum number of aptitude tests before the model trusts a juror grade. This avoids overreacting to one lucky or unlucky result." },
    { id: "keyJurorShare", category: "Juror aptitude tests", label: "Graded test seats targeted per juror", min: .1, max: 2, step: .05, default: .5, low: .25, high: 1, format: "number", confidence: "medium", affects: ["drift"], copy: "What it means: The court-level target for independently graded aptitude-test seats as the eligible juror pool grows." },
    { id: "reputationSkillLift", category: "Juror aptitude tests", label: "Accuracy boost from reputation", min: 0, max: .08, step: .005, default: 0, low: 0, high: .04, format: "pct", confidence: "scaled design rail", affects: ["panel", "safety"], copy: "What it means: The modeled accuracy increase from giving more influence to high-reputation jurors. It is 0% by default in the baseline." },
    { id: "rewardEligibleShare", category: "Long-term juror rewards", label: "Jurors eligible for rewards", min: .2, max: 1, step: .05, default: .65, low: .4, high: .85, format: "pct", confidence: "medium", affects: ["supply", "panel"], copy: "What it means: The share of jurors who keep high enough grades to remain eligible for long-term rewards." },
    { id: "rewardRetentionCredit", category: "Long-term juror rewards", label: "How much future rewards keep jurors", min: 0, max: 1, step: .05, default: .7, low: .35, high: 1, format: "pct", confidence: "low", affects: ["supply", "capture"], copy: "What it means: How much jurors value future rewards when deciding whether money at risk is worth the hassle." },
    { id: "rewardRetentionLift", category: "Long-term juror rewards", label: "Retention boost from rewards", min: 0, max: .25, step: .01, default: .08, low: .03, high: .16, format: "pct", confidence: "low", affects: ["supply", "capture"], copy: "What it means: The extra juror retention created by long-term rewards instead of only single-verdict payouts." },
    { id: "rewardSkillLift", category: "Long-term juror rewards", label: "Accuracy boost from rewards", min: 0, max: .08, step: .005, default: .025, low: .005, high: .05, format: "pct", confidence: "low", affects: ["panel", "safety"], copy: "What it means: The modeled accuracy lift from motivating jurors with long-term rewards." },
    { id: "rewardSignalScale", category: "Long-term juror rewards", label: "Reward size needed to matter", min: .1, max: 2, step: .05, default: .45, low: .25, high: .9, format: "number", confidence: "low", affects: ["supply", "panel"], copy: "What it means: How large rewards need to be, relative to base pay, before they noticeably improve juror retention or effort." },
    { id: "appealCaptureMultiplier", category: "Appeal costs and delay", label: "Appeal cost boost when control risk is high", min: .5, max: 5, step: .25, default: 2, low: 1, high: 3.5, format: "mult", confidence: "medium", affects: ["appeal", "grief"], copy: "What it means: A pricing rule that raises appeal costs when attacker-control risk is high, making it harder to buy your way up the appeal path." },
    { id: "appealDelayRate", category: "Appeal costs and delay", label: "Weekly cost for delaying payout", min: .001, max: .02, step: .001, default: .01, low: .004, high: .016, format: "pct", confidence: "medium", affects: ["appeal", "grief"], copy: "What it means: The weekly cost charged to an appellant as a percentage of the case value. It pays for the time value of locking up the winner's funds." },
    { id: "griefDelayRate", category: "Appeal costs and delay", label: "Weekly value of a delay attack", min: .001, max: .025, step: .001, default: .008, low: .004, high: .016, format: "pct", confidence: "low", affects: ["grief"], copy: "What it means: The weekly value, as a percentage of case size, that a malicious party gains by delaying the outcome." },
    { id: "petitionMultiplier", category: "Appeal costs and delay", label: "Extra security for another appeal", min: 1, max: 1.6, step: .05, default: 1, low: 1, high: 1.3, format: "mult", confidence: "scaled design rail", affects: ["appeal", "grief"], copy: "What it means: A multiplier on the anti-re-roll security target for another appeal round. It never marks up or discounts the panel-work and delay service fee." },
    { id: "finalityAuditDrag", category: "Appeal costs and delay", label: "Delay attack reduced by later audits", min: 0, max: .6, step: .05, default: 0, low: 0, high: .35, format: "pct", confidence: "scaled design rail", affects: ["grief"], copy: "What it means: The reduction in expected delay benefit if later audits can identify and punish collusive attackers." }
];

if (typeof window !== "undefined") {
  window.ASSUMPTIONS = ASSUMPTIONS;
}
