// Generates typed viem ABIs from the Foundry build output into src/abi/.
// Run from web/:  pnpm gen:contracts   (requires `forge build` in ../contracts).
// The generated files are committed so CI (which does not run forge) can build.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const OUT = '../contracts/out';
const CONTRACTS = [
  'MockUSD',
  'JurorRegistry',
  'DisputeCourt',
  'DealEscrow',
  'RewardPool',
  'MockSybilGate',
];

mkdirSync('src/abi', { recursive: true });
const index = [];
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(`${OUT}/${name}.sol/${name}.json`, 'utf8'));
  const camel = name[0].toLowerCase() + name.slice(1) + 'Abi';
  writeFileSync(
    `src/abi/${name}.ts`,
    `// AUTO-GENERATED by \`pnpm gen:contracts\`. Do not edit by hand.\n` +
      `export const ${camel} = ${JSON.stringify(artifact.abi)} as const;\n`,
  );
  index.push(`export { ${camel} } from './${name}';`);
  console.log(`wrote src/abi/${name}.ts (${artifact.abi.length} entries)`);
}
writeFileSync('src/abi/index.ts', `// AUTO-GENERATED by \`pnpm gen:contracts\`.\n` + index.join('\n') + '\n');
console.log('wrote src/abi/index.ts');
